# Generated by Django 4.0.5 on 2022-07-07 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=255, verbose_name='Nacionalidad')),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Persona',
                'db_table': 'Person',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('logo_image_b64', models.BinaryField(blank=True)),
                ('shield_image_b64', models.BinaryField(blank=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'db_table': 'Team',
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Asistencia', 'Asistencia'), ('Medico', 'Medico'), ('Preparador', 'Preparador')], max_length=255, verbose_name='Rol')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff', related_query_name='person_staff', to='fifa.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_team', related_query_name='staff_team', to='fifa.team')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('position', models.CharField(choices=[('Arquero', 'Arquero'), ('Defensa', 'Defensa'), ('Mediocampo', 'Mediocampo'), ('Delantero', 'Delantero')], max_length=255, verbose_name='Posicion')),
                ('number', models.IntegerField(blank=True, null=True)),
                ('starter', models.BooleanField(default=False, verbose_name='Titular')),
                ('photo_image_b64', models.BinaryField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_player', related_query_name='person_player', to='fifa.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_team', related_query_name='player_team', to='fifa.team')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'db_table': 'Player',
            },
        ),
    ]
