# Generated by Django 4.0.5 on 2022-07-01 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
