# Generated by Django 4.0.5 on 2022-07-02 00:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0002_alter_team_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=255, verbose_name='Nacionalidad')),
                ('role', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Asistencia', 'Asistencia'), ('Medico', 'Medico'), ('Preparador', 'Preparador')], max_length=255, verbose_name='Rol')),
            ],
            options={
                'db_table': 'Manager',
            },
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Jugador', 'verbose_name_plural': 'Jugadores'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.AlterModelTable(
            name='player',
            table='Player',
        ),
        migrations.AlterModelTable(
            name='team',
            table='Team',
        ),
        migrations.DeleteModel(
            name='Staff',
        ),
        migrations.AddField(
            model_name='manager',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manager_team', related_query_name='manager_team', to='fifa.team'),
        ),
    ]
