# Generated by Django 4.0.5 on 2022-07-02 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0003_manager_alter_player_options_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
