# Generated by Django 4.0.5 on 2022-07-06 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fifa', '0004_alter_manager_updated_at_alter_player_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(max_length=255, verbose_name='Nacionalidad')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('role', models.CharField(choices=[('Tecnico', 'Tecnico'), ('Asistencia', 'Asistencia'), ('Medico', 'Medico'), ('Preparador', 'Preparador')], max_length=255, verbose_name='Rol')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_staff', related_query_name='person_staff', to='fifa.person')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_team', related_query_name='staff_team', to='fifa.team')),
            ],
            options={
                'db_table': 'Staff',
            },
        ),
        migrations.RemoveField(
            model_name='player',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='player',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='player',
            name='name',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='player',
            name='person',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='person_player', related_query_name='person_player', to='fifa.person'),
            preserve_default=False,
        ),
    ]
